namespace Bybit.Api.Asset;

/// <summary>
/// Create universal transfer request.
/// </summary>
public record BybitAssetUniversalTransferRequest
{
    /// <summary>
    /// Initializes a new universal transfer request.
    /// </summary>
    /// <param name="asset">Coin name, uppercase only.</param>
    /// <param name="quantity">Transfer amount.</param>
    /// <param name="fromMemberId">Source UID.</param>
    /// <param name="toMemberId">Destination UID.</param>
    /// <param name="fromAccount">Source account type.</param>
    /// <param name="toAccount">Destination account type.</param>
    public BybitAssetUniversalTransferRequest(string asset, decimal quantity, string fromMemberId, string toMemberId, BybitAccountType fromAccount, BybitAccountType toAccount)
    {
        Asset = asset;
        Quantity = quantity;
        FromMemberId = fromMemberId;
        ToMemberId = toMemberId;
        FromAccount = fromAccount;
        ToAccount = toAccount;
    }

    /// <summary>
    /// Coin name, uppercase only.
    /// </summary>
    [JsonProperty("coin")]
    public string Asset { get; set; }

    /// <summary>
    /// Transfer amount.
    /// </summary>
    [JsonProperty("amount"), JsonConverter(typeof(DecimalToStringConverter))]
    public decimal Quantity { get; set; }

    /// <summary>
    /// Source UID.
    /// </summary>
    [JsonProperty("fromMemberId")]
    public string FromMemberId { get; set; }

    /// <summary>
    /// Destination UID.
    /// </summary>
    [JsonProperty("toMemberId")]
    public string ToMemberId { get; set; }

    /// <summary>
    /// Source account type.
    /// </summary>
    [JsonProperty("fromAccountType")]
    public BybitAccountType FromAccount { get; set; }

    /// <summary>
    /// Destination account type.
    /// </summary>
    [JsonProperty("toAccountType")]
    public BybitAccountType ToAccount { get; set; }

    /// <summary>
    /// Transfer ID. If omitted, one will be generated by the client flow.
    /// </summary>
    [JsonProperty("transferId", NullValueHandling = NullValueHandling.Ignore)]
    public string? TransferId { get; set; }
}
