namespace Bybit.Api.Asset;

/// <summary>
/// Create internal transfer request.
/// </summary>
public record BybitAssetInternalTransferRequest
{
    /// <summary>
    /// Initializes a new internal transfer request.
    /// </summary>
    /// <param name="asset">Coin name, uppercase only.</param>
    /// <param name="quantity">Transfer amount.</param>
    /// <param name="fromAccount">Source account type.</param>
    /// <param name="toAccount">Destination account type.</param>
    public BybitAssetInternalTransferRequest(string asset, decimal quantity, BybitAccountType fromAccount, BybitAccountType toAccount)
    {
        Asset = asset;
        Quantity = quantity;
        FromAccount = fromAccount;
        ToAccount = toAccount;
    }

    /// <summary>
    /// Coin name, uppercase only.
    /// </summary>
    [JsonProperty("coin")]
    public string Asset { get; set; }

    /// <summary>
    /// Transfer amount.
    /// </summary>
    [JsonProperty("amount"), JsonConverter(typeof(DecimalToStringConverter))]
    public decimal Quantity { get; set; }

    /// <summary>
    /// Source account type.
    /// </summary>
    [JsonProperty("fromAccountType")]
    public BybitAccountType FromAccount { get; set; }

    /// <summary>
    /// Destination account type.
    /// </summary>
    [JsonProperty("toAccountType")]
    public BybitAccountType ToAccount { get; set; }

    /// <summary>
    /// Transfer ID. If omitted, one will be generated by the client flow.
    /// </summary>
    [JsonProperty("transferId", NullValueHandling = NullValueHandling.Ignore)]
    public string? TransferId { get; set; }
}
